### ISSUE TITLE
Don't store buffer-file-name?

### ISSUE THREAD

**Issue by dgutov** [company-mode/company-statistics#2]
It seems to me it fattens the database unnecessarily. Do you really consider having different statistics between different files in the same major mode, in the same project, important?

If the database has space to spare, I'd try to store more context instead. Such as "previous word", or "last preceding keyword".

**Comment by ilohmar** [comment]
It is surely not very space-effective.  My current cache file (default settings) weighs in at 68k.  I mostly included the filename since I could, and it makes some sense to me: The project is not used and would be nice instead, but as there are several project packages (for example, I use my own unpublished one), it would be unwise to include such a thing in the default function.

But I will gladly try something else, and I like your suggestions.  It might be difficult to get the last keyword in arbitrary modes (although it can always be left out, of course), but the preceding symbol should be easy.  I will play with that..

**Comment by dgutov** [comment]
> but as there are several project packages

We could leave that feature to each project, then (such as pointing `company-statistics-file` to the project-local location, then different project won't share statistics). Or maybe wait until Emacs finally grows a project API, look up the project root, and save that instead of the file paths.

> It might be difficult to get the last keyword in arbitrary modes

Should be straightforward if you rely on font-lock. You can use `(previous-single-property-change (point) 'face)` to take the closest region that has the value `font-lock-keyword-face`.

**Comment by ilohmar** [comment]
Yeah, that's nice, I use a lot of project-local vars myself..

I keep forgetting the font-lock-approach, although I have dealt with it before (and cc-mode does a lot of this stuff).  I'll keep that in mind and will try to use the last keyword, plus a directly preceding symbol if only separated by punctuation (no whitespace), like a namespace or object etc.

**Comment by vjohansen** [comment]
Regarding the original question:

Maybe use the directory instead of the filename?

(file-name-directory (buffer-file-name)) vs buffer-file-name

**Comment by ilohmar** [comment]
Sorry for a long break... Directory name might also be useful, but this is all up to the user, of course.  I have a new version locally which offers a default-configured 'heavy' (including last keyword etc) and a 'light' variant; just did not get around to adjusting the tests.  Soon, I hope!

**Comment by ilohmar** [comment]
I just pushed version 0.2.0 with the changes mentioned above.  I'd be very happy if there's anybody out there who is using the package, and could even provide some feedback.  In any case, I will push this to the GNU elpa soon-ish..

**Comment by ilohmar** [comment]
The new approach is relatively flexible and there at least some people who use it and have not (yet) complained.  So I'm closing this for the time being.
